# Generated by Django 4.0.6 on 2022-07-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('usertype', models.IntegerField(choices=[(0, 'Telegram'), (1, 'Discord')])),
                ('tgid', models.IntegerField(blank=True, default=0, null=True)),
                ('disid', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
