# Generated by Django 4.0.6 on 2022-07-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_botuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotUser',
            new_name='User',
        ),
    ]
