# Generated by Django 4.0.6 on 2022-07-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_quiz_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option0',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
