# Generated by Django 4.0.6 on 2022-07-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_option0_alter_question_option1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('usertype', 'tgid', 'disid')},
        ),
    ]
